#!perl

use strict;
use warnings;
use Test::Fixture::DBI::Console;

my $type = shift || die usage();
my $console = Test::Fixture::DBI::Console->new( database => $type )->run();

sub usage {
    print <<EOM;
Usage: $0 database_type
	database_type - mysql|sqlite
EOM
}
